image: python:3.6.0

pages:
  script:
  - apt-get update && apt-get install -y python3-dev python3-setuptools libtiff5-dev libjpeg62-turbo-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
  - pip install nikola
  - nikola build
  artifacts:
    paths:
    - public
  only:
  - master