sudo: required

language: python
python: "3.6"

script:
  - pip install pipenv
  - pipenv install
  - pipenv run nikola build

install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
