baseurl = "https://www.christianbarra.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 10
title = "Christian Barra"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "red"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 10
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  favicon = "img/favicon/favicon.ico"

[languages]
  [languages.en]
    title = "Christian Barra"
    subtitle = ""
    keywords = ""
    copyright = "CC BY-SA 4.0"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoHomeLink = "/"
